### ISSUE TITLE
Symbol rate of the m17_coder

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/gr-m17#2]
In the block, `samp_rate` is set to 14.4e3 as the default value. To get it to work with a Root Raised Cosine block, one has to put an additional Throttle in between and set it to the correct symbol rate, which is 4.8e3.

**Comment by jmfriedt** [comment]
At the moment the sampling rate is not used since the number of output values is hardcoded as
```       
for(uint16_t i=0; i<(int)(192/2); i++) //40ms * 4800 = 192
```
I am confused because the coder block outputs 24 times more items than input data so that an output sampling rate of 4800 Hz means an input rate of 200 bits/s or 25 bytes/s. Is this correct?

The datarate will only be determined by hardware Sink rate and the various interpolations between m17_coder and this output, not by the Throttle block. Using properly input rate and output rate should be implemented (as is done for example in the NBFM Transmit with its audio rate and quadrature rate).

**Comment by sp5wwp** [comment]
I would remove the `samp_rate` setting anyway. The value is fixed, a constant set by the specification. Otherwise, everything looks correct.

**Comment by jmfriedt** [comment]
All references to sampling rate removed in aaefa3334e82f779bcea3650279b704628847df5
